[2023-09-06T21:11:08.596-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: streamings-dag.data_management manual__2023-09-07T00:03:56.705073+00:00 [queued]>
[2023-09-06T21:11:08.603-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: streamings-dag.data_management manual__2023-09-07T00:03:56.705073+00:00 [queued]>
[2023-09-06T21:11:08.603-0300] {taskinstance.py:1361} INFO - Starting attempt 2 of 3
[2023-09-06T21:11:08.621-0300] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_management> on 2023-09-07 00:03:56.705073+00:00
[2023-09-06T21:11:08.624-0300] {standard_task_runner.py:57} INFO - Started process 11244 to run task
[2023-09-06T21:11:08.627-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'streamings-dag', 'data_management', 'manual__2023-09-07T00:03:56.705073+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/streamings-dag.py', '--cfg-path', '/tmp/tmpb266pn9_']
[2023-09-06T21:11:08.628-0300] {standard_task_runner.py:85} INFO - Job 13: Subtask data_management
[2023-09-06T21:11:08.671-0300] {task_command.py:415} INFO - Running <TaskInstance: streamings-dag.data_management manual__2023-09-07T00:03:56.705073+00:00 [running]> on host dany.
[2023-09-06T21:11:08.731-0300] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='danielbcuadros@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='streamings-dag' AIRFLOW_CTX_TASK_ID='data_management' AIRFLOW_CTX_EXECUTION_DATE='2023-09-07T00:03:56.705073+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-07T00:03:56.705073+00:00'
[2023-09-06T21:11:08.732-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-06T21:11:08.732-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/dany/airflow/dags/../../Streaming-insights/venv/bin/python /home/dany/airflow/dags/../../Streaming-insights/etls/data-management.py']
[2023-09-06T21:11:08.737-0300] {subprocess.py:86} INFO - Output:
[2023-09-06T21:11:09.412-0300] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-09-06T21:11:09.412-0300] {subprocess.py:93} INFO -   File "/home/dany/airflow/dags/../../Streaming-insights/etls/data-management.py", line 142, in <module>
[2023-09-06T21:11:09.412-0300] {subprocess.py:93} INFO -     factory = DataManagement()
[2023-09-06T21:11:09.412-0300] {subprocess.py:93} INFO -   File "/home/dany/airflow/dags/../../Streaming-insights/etls/data-management.py", line 33, in __init__
[2023-09-06T21:11:09.413-0300] {subprocess.py:93} INFO -     self.engine = create_engine(connection_string)
[2023-09-06T21:11:09.413-0300] {subprocess.py:93} INFO -   File "<string>", line 2, in create_engine
[2023-09-06T21:11:09.413-0300] {subprocess.py:93} INFO -   File "/home/dany/Streaming-insights/venv/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
[2023-09-06T21:11:09.413-0300] {subprocess.py:93} INFO -     return fn(*args, **kwargs)
[2023-09-06T21:11:09.413-0300] {subprocess.py:93} INFO -   File "/home/dany/Streaming-insights/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 544, in create_engine
[2023-09-06T21:11:09.413-0300] {subprocess.py:93} INFO -     dbapi = dialect_cls.dbapi(**dbapi_args)
[2023-09-06T21:11:09.413-0300] {subprocess.py:93} INFO -   File "/home/dany/Streaming-insights/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 811, in dbapi
[2023-09-06T21:11:09.414-0300] {subprocess.py:93} INFO -     import psycopg2
[2023-09-06T21:11:09.414-0300] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'psycopg2'
[2023-09-06T21:11:09.516-0300] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-06T21:11:09.525-0300] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dany/airflow/airflow-venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-06T21:11:09.528-0300] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=streamings-dag, task_id=data_management, execution_date=20230907T000356, start_date=20230907T001108, end_date=20230907T001109
[2023-09-06T21:11:09.547-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task data_management (Bash command failed. The command returned a non-zero exit code 1.; 11244)
[2023-09-06T21:11:09.564-0300] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-06T21:11:09.580-0300] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
